import 'dotenv/config';
import express, { NextFunction, Request, Response } from 'express';
import cors from 'cors';
import multer from 'multer';
import cron from 'node-cron';
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { z } from 'zod';
import webPush from 'web-push';

type Role = 'founder_finance'|'cofounder'|'account_manager'|'creator';
type AuthRequest = Request & { user?: { id:string; email:string; role:Role; creatorId?:string } };
const app=express(), upload=multer({storage:multer.memoryStorage(),limits:{fileSize:12*1024*1024}});
const supabase: SupabaseClient = createClient(process.env.SUPABASE_URL || 'https://placeholder.supabase.co',process.env.SUPABASE_SERVICE_ROLE_KEY || 'placeholder');
const vapidPublicKey=process.env.VAPID_PUBLIC_KEY, vapidPrivateKey=process.env.VAPID_PRIVATE_KEY;
if(vapidPublicKey&&vapidPrivateKey){webPush.setVapidDetails(process.env.VAPID_SUBJECT || 'mailto:admin@yosomedia.in',vapidPublicKey,vapidPrivateKey);console.info('push:init',{configured:true,subject:process.env.VAPID_SUBJECT || 'mailto:admin@yosomedia.in'});}else console.warn('push:init',{configured:false,missing:{publicKey:!vapidPublicKey,privateKey:!vapidPrivateKey}});
const configuredOrigins=(process.env.FRONTEND_URL||'http://localhost:5173').split(',').map(origin=>origin.trim().replace(/\/$/,'')).filter(Boolean);
const vercelOrigin=/^https:\/\/yoso-creator-platform(?:-[a-z0-9-]+)?\.vercel\.app$/i;
app.use(cors({origin:(origin,callback)=>{if(!origin)return callback(null,true);const normalized=origin.replace(/\/$/,'');if(configuredOrigins.includes(normalized)||vercelOrigin.test(normalized))return callback(null,true);callback(null,false);}})); app.use(express.json());
const deny=(res:Response)=>res.status(403).json({error:'You do not have access to this resource.'});
async function auth(req:AuthRequest,res:Response,next:NextFunction){const token=/^Bearer\s+(.+)$/i.exec(req.headers.authorization||'')?.[1];if(!token)return res.status(401).json({error:'Missing session'});const {data,error}=await supabase.auth.getUser(token);if(error||!data.user)return res.status(401).json({error:'Invalid session'});const email=data.user.email!;let {data:user}=await supabase.from('users').select('*').eq('email',email).maybeSingle();if(!user){const {data:newUser,error:insertError}=await supabase.from('users').insert({email,name:data.user.user_metadata?.full_name,role:'creator'}).select().single();if(insertError)return next(insertError);user=newUser;}const {data:creator}=await supabase.from('creators').select('id').eq('email',email).maybeSingle();req.user={id:user.id,email,role:user.role,creatorId:creator?.id};next();}
const roles=(...allowed:Role[])=>(req:AuthRequest,res:Response,next:NextFunction)=>req.user&&allowed.includes(req.user.role)?next():deny(res);
const admin=roles('founder_finance','cofounder'), staff=roles('founder_finance','cofounder','account_manager'), creator=roles('creator');
const month=(d=new Date())=>({key:new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10),label:d.toLocaleString('en-IN',{month:'long',year:'2-digit',timeZone:'Asia/Kolkata'}).replace(' ','\'')});
async function notifyCreator(creatorId:string,body:string,meta:Record<string,unknown>={}){
  console.info('push:notify:start',{creatorId,configured:!!(vapidPublicKey&&vapidPrivateKey),...meta});
  if(!vapidPublicKey||!vapidPrivateKey)return {attempted:0,sent:0,failed:0,reason:'missing-vapid'};
  const {data,error}=await supabase.from('push_subscriptions').select('id,endpoint,p256dh,auth').eq('creator_id',creatorId);
  if(error){console.error('push:notify:load-failed',{creatorId,error:error.message,...meta});return {attempted:0,sent:0,failed:0,reason:'load-failed'};}
  console.info('push:notify:subscriptions',{creatorId,count:data?.length||0});
  const payload=JSON.stringify({title:'YOSO task assigned',body,url:'/',timestamp:new Date().toISOString(),...meta});
  let sent=0,failed=0;
  for(const row of data||[]){
    const subscription={endpoint:row.endpoint,keys:{p256dh:row.p256dh,auth:row.auth}};
    try{const result=await webPush.sendNotification(subscription,payload,{TTL:300,urgency:'high',topic:'yoso-task'});sent++;console.info('push:notify:accepted',{creatorId,subscriptionId:row.id,statusCode:result?.statusCode,endpointHost:new URL(row.endpoint).host,...meta});}
    catch(err:any){failed++;console.error('push:notify:send-failed',{creatorId,subscriptionId:row.id,statusCode:err?.statusCode,message:err?.message,body:err?.body,...meta});if(err?.statusCode===404||err?.statusCode===410){await supabase.from('push_subscriptions').delete().eq('id',row.id);console.warn('push:notify:deleted-expired-subscription',{creatorId,subscriptionId:row.id});}}
  }
  const summary={attempted:data?.length||0,sent,failed};
  console.info('push:notify:complete',{creatorId,...summary,...meta});
  return summary;
}
async function createTaskForCreator(post:any,creatorId:string,type:'repost'|'comment'){const {data:task,error}=await supabase.from('tasks').insert({post_id:post.id,creator_id:creatorId,type}).select('id').single();if(error){console.error('task:assign:failed',{postId:post.id,creatorId,type,error:error.message});return;}console.info('task:assign:created',{taskId:task.id,postId:post.id,creatorId,type});await notifyCreator(creatorId,`New ${type} task for ${post.client} - respond within 2 hours.`,{event:'task-assigned',taskId:task.id,postId:post.id,type,client:post.client});}
async function selectCreator(postId:string,type:'repost'|'comment',mode:string,industry?:string,exclude:string[]=[]){let q=supabase.from('creators').select('id').eq('status','active').not('id','in',`(${exclude.join(',')||'00000000-0000-0000-0000-000000000000'})`);if(mode==='industry'&&industry)q=q.eq('industry',industry);const {data}=await q; if(!data?.length)return null; if(mode!=='random')return data[0]; const start=new Date();start.setDate(1);const {data:tasks}=await supabase.from('tasks').select('creator_id').gte('assigned_at',start.toISOString());const counts=new Map<string,number>();tasks?.forEach(t=>counts.set(t.creator_id,(counts.get(t.creator_id)||0)+1));return [...data].sort((a,b)=>(counts.get(a.id)||0)-(counts.get(b.id)||0))[0];}
async function assign(post:any,type:'repost'|'comment'){const {data:old}=await supabase.from('tasks').select('creator_id').eq('post_id',post.id).eq('type',type);const pick=await selectCreator(post.id,type,post.targeting_mode,post.target_industry,old?.map(x=>x.creator_id));if(!pick){console.warn('task:assign:no-creator',{postId:post.id,type,mode:post.targeting_mode,industry:post.target_industry});return;}await createTaskForCreator(post,pick.id,type);}
async function reassign(task:any){const {data:post}=await supabase.from('posts').select('*').eq('id',task.post_id).single();if(!post||post.status==='closed')return;const {count}=await supabase.from('tasks').select('*',{count:'exact',head:true}).eq('post_id',post.id).eq('type',task.type).eq('state','done');const quota=task.type==='repost'?post.repost_quota:post.comment_quota;if((count||0)<quota)await assign(post,task.type);}
const currentUser=(req:AuthRequest,res:Response)=>res.json(req.user);
app.get('/me',auth,currentUser);
app.get('/api/me',auth,currentUser);
app.post('/push/subscribe',auth,creator,async(req:AuthRequest,res,next)=>{try{const b=z.object({endpoint:z.string().url(),keys:z.object({p256dh:z.string().min(1),auth:z.string().min(1)})}).parse(req.body);console.info('push:subscribe:request',{userId:req.user!.id,creatorId:req.user!.creatorId,endpoint:b.endpoint.slice(0,80)});if(!req.user!.creatorId)return res.status(400).json({error:'Complete onboarding before enabling push notifications.'});const values={user_id:req.user!.id,creator_id:req.user!.creatorId,endpoint:b.endpoint,p256dh:b.keys.p256dh,auth:b.keys.auth,user_agent:req.headers['user-agent'] || null,updated_at:new Date().toISOString()};const {data,error}=await supabase.from('push_subscriptions').upsert(values,{onConflict:'endpoint'}).select('id,endpoint,updated_at').single();if(error)throw error;console.info('push:subscribe:saved',{subscriptionId:data.id,creatorId:req.user!.creatorId});res.status(201).json(data);}catch(e){next(e)}});
app.post('/push/test',auth,creator,async(req:AuthRequest,res,next)=>{try{if(!req.user!.creatorId)return res.status(400).json({error:'Complete onboarding before testing push notifications.'});const summary=await notifyCreator(req.user!.creatorId,'This is a test push from YOSO.',{event:'test-push',requestedBy:req.user!.id});res.json(summary);}catch(e){next(e)}});
app.post('/users',auth,admin,async(req,res,next)=>{try{const b=z.object({email:z.string().email(),name:z.string().optional(),role:z.enum(['founder_finance','cofounder','account_manager','creator'])}).parse(req.body);const {data,error}=await supabase.from('users').upsert(b,{onConflict:'email'}).select().single();if(error)throw error;res.status(201).json(data);}catch(e){next(e)}});
const profile=z.object({name:z.string().min(1),industry:z.string().optional(),region:z.string().optional(),followers:z.number().int().nonnegative().optional(),linkedin_url:z.string().url().optional(),bank_account:z.string().optional(),ifsc:z.string().optional()});
const creatorSelfSelect='id,name,email,industry,region,followers,linkedin_url,bank_account,ifsc,status,onboarded_at,created_at';
app.post('/creators/onboard',auth,creator,async(req:AuthRequest,res,next)=>{try{const p=profile.parse(req.body);const record={...p,email:req.user!.email,user_id:req.user!.id,onboarded_at:new Date().toISOString()};const {data,error}=await supabase.from('creators').upsert(record,{onConflict:'email'}).select(creatorSelfSelect).single();if(error)throw error;res.json(data);}catch(e){next(e)}});
app.get('/creators/me',auth,creator,async(req:AuthRequest,res,next)=>{try{const {data,error}=await supabase.from('creators').select(creatorSelfSelect).eq('email',req.user!.email).maybeSingle();if(error)throw error;if(!data)return res.status(404).json({error:'Creator profile not found'});res.json(data);}catch(e){next(e)}});
app.patch('/creators/me',auth,creator,async(req:AuthRequest,res,next)=>{try{const p=profile.partial().parse(req.body);const {data,error}=await supabase.from('creators').update(p).eq('email',req.user!.email).select(creatorSelfSelect).single();if(error)throw error;res.json(data);}catch(e){next(e)}});
app.get('/creators',auth,staff,async(req:AuthRequest,res,next)=>{try{const select=req.user!.role==='account_manager'?'id,name,email,industry,region,followers,linkedin_url,status,created_at':'*';let q=supabase.from('creators').select(select).order('name');if(req.query.industry)q=q.eq('industry',req.query.industry);const {data,error}=await q;if(error)throw error;res.json(data);}catch(e){next(e)}});
app.patch('/creators/:id/rates',auth,admin,async(req,res,next)=>{try{const b=z.object({rate_repost:z.number().nonnegative(),rate_comment:z.number().nonnegative(),rate_campaign:z.number().nonnegative()}).parse(req.body);const {data,error}=await supabase.from('creators').update(b).eq('id',req.params.id).select().single();if(error)throw error;res.json(data)}catch(e){next(e)}});
app.patch('/creators/:id/status',auth,admin,async(req,res,next)=>{try{const b=z.object({status:z.enum(['active','inactive'])}).parse(req.body);const {data,error}=await supabase.from('creators').update(b).eq('id',req.params.id).select().single();if(error)throw error;res.json(data)}catch(e){next(e)}});
app.post('/posts',auth,staff,async(req:AuthRequest,res,next)=>{try{const b=z.object({client:z.string().min(1),link:z.string().url(),repost_quota:z.number().int().nonnegative(),comment_quota:z.number().int().nonnegative(),targeting_mode:z.enum(['specific','industry','random']),target_industry:z.string().optional(),specific_creator_ids:z.array(z.string().uuid()).optional()}).parse(req.body);const {data:post,error}=await supabase.from('posts').insert({...b,created_by:req.user!.id}).select().single();if(error)throw error;if(b.targeting_mode==='specific'){for(const id of b.specific_creator_ids||[]){await createTaskForCreator(post,id,'repost');await createTaskForCreator(post,id,'comment');}}else{for(let i=0;i<b.repost_quota;i++)await assign(post,'repost');for(let i=0;i<b.comment_quota;i++)await assign(post,'comment');}res.status(201).json(post);}catch(e){next(e)}});
app.get('/posts',auth,staff,async(_req,res,next)=>{try{const {data,error}=await supabase.from('posts').select('*,tasks(*)').order('created_at',{ascending:false});if(error)throw error;res.json(data)}catch(e){next(e)}}); app.post('/posts/:id/close',auth,staff,async(req,res,next)=>{try{const {data,error}=await supabase.from('posts').update({status:'closed',closed_at:new Date().toISOString()}).eq('id',req.params.id).select().single();if(error)throw error;res.json(data)}catch(e){next(e)}});
app.get('/tasks/mine',auth,creator,async(req:AuthRequest,res,next)=>{try{const {data,error}=await supabase.from('tasks').select('*,posts(client,link)').eq('creator_id',req.user!.creatorId!).order('assigned_at',{ascending:false});if(error)throw error;res.json(data)}catch(e){next(e)}});
app.post('/tasks/:id/screenshot',auth,creator,upload.single('screenshot'),async(req:AuthRequest,res,next)=>{try{const {data:task}=await supabase.from('tasks').select('*').eq('id',req.params.id).eq('creator_id',req.user!.creatorId!).single();if(!task)return deny(res);/* TODO: upload to Google Drive and call Claude screenshot reader */const {data,error}=await supabase.from('tasks').update({state:'done',responded_at:new Date().toISOString(),screenshot_url:`drive://pending/${req.file?.originalname||'screenshot'}`}).eq('id',task.id).select().single();if(error)throw error;res.json(data)}catch(e){next(e)}});
app.post('/tasks/:id/reject',auth,creator,async(req:AuthRequest,res,next)=>{try{const {data:task,error}=await supabase.from('tasks').update({state:'rejected',responded_at:new Date().toISOString(),reject_reason:req.body.reason||null}).eq('id',req.params.id).eq('creator_id',req.user!.creatorId!).select().single();if(error)throw error;await reassign(task);res.json(task)}catch(e){next(e)}});
app.post('/invoices/upload',auth,creator,upload.single('invoice'),async(req:AuthRequest,res,next)=>{try{const m=month();const {data:done}=await supabase.from('tasks').select('type').eq('creator_id',req.user!.creatorId!).eq('state','done');const reposts=done?.filter(t=>t.type==='repost').length||0,comments=done?.filter(t=>t.type==='comment').length||0;const {data:c}=await supabase.from('creators').select('rate_repost,rate_comment').eq('id',req.user!.creatorId!).single();const amount=c?.rate_repost!=null&&c?.rate_comment!=null?reposts*c.rate_repost+comments*c.rate_comment:null;/* TODO: archive PDF in monthly Drive folder + Claude bank extraction */const {data,error}=await supabase.from('invoices').upsert({creator_id:req.user!.creatorId,month_label:m.label,month_key:m.key,reposts,comments,amount,invoice_url:`drive://pending/${req.file?.originalname}`,uploaded_at:new Date().toISOString()},{onConflict:'creator_id,month_label'}).select().single();if(error)throw error;res.json(data)}catch(e){next(e)}});
app.get('/invoices/mine',auth,creator,async(req:AuthRequest,res,next)=>{try{const {data,error}=await supabase.from('invoices').select('*').eq('creator_id',req.user!.creatorId!).order('month_key',{ascending:false});if(error)throw error;res.json(data)}catch(e){next(e)}});
app.get('/invoices',auth,admin,async(req,res,next)=>{try{let q=supabase.from('invoices').select('*,creators(name,email,bank_account,ifsc)').order('month_key',{ascending:false});if(req.query.month)q=q.eq('month_label',req.query.month);const {data,error}=await q;if(error)throw error;res.json(data)}catch(e){next(e)}});
for(const [path,change] of [['approve',{approval_state:'approved'}],['reject',{approval_state:'rejected'}],['pay',{paid:true,paid_on:new Date().toISOString().slice(0,10)}]] as const)app.patch(`/invoices/:id/${path}`,auth,admin,async(req:AuthRequest,res,next)=>{try{const values=path==='reject'?{...change,reject_reason:z.object({reason:z.string().min(1)}).parse(req.body).reason}:change;const {data,error}=await supabase.from('invoices').update(values).eq('id',req.params.id).select().single();if(error)throw error;if(path==='pay')await supabase.from('payments_log').insert({invoice_id:data.id,amount:data.amount,paid_by:req.user!.id});res.json(data)}catch(e){next(e)}});
app.get('/invoices/export',auth,admin,async(req,res,next)=>{try{const {data,error}=await supabase.from('invoices').select('amount,creators(name,bank_account,ifsc)').eq('month_label',req.query.month).eq('approval_state','approved').eq('paid',false);if(error)throw error;res.type('text/csv').attachment(`yoso-bank-${req.query.month}.csv`).send(['Creator Name,Bank Account No.,IFSC Code,Amount',...(data||[]).map((x:any)=>`"${x.creators.name}","${x.creators.bank_account}","${x.creators.ifsc}",${x.amount}`)].join('\n'));}catch(e){next(e)}});
app.get('/dashboard/ops',auth,staff,async(_req,res,next)=>{try{const [{count:active},{count:inactive},{data:tasks}]=await Promise.all([supabase.from('creators').select('*',{count:'exact',head:true}).eq('status','active'),supabase.from('creators').select('*',{count:'exact',head:true}).eq('status','inactive'),supabase.from('tasks').select('creator_id,type,state')]);res.json({active,inactive,tasks});}catch(e){next(e)}});
app.get('/dashboard/money',auth,admin,async(_req,res,next)=>{try{const {data,error}=await supabase.from('invoices').select('month_label,amount,paid,bank_match,approval_state');if(error)throw error;res.json(data)}catch(e){next(e)}});
cron.schedule('* * * * *',async()=>{const {data}=await supabase.from('tasks').update({state:'timeout',responded_at:new Date().toISOString()}).eq('state','sent').lt('expires_at',new Date().toISOString()).select();for(const t of data||[])await reassign(t);},{timezone:'Asia/Kolkata'});
cron.schedule('*/5 * * * *',async()=>{const {data:posts}=await supabase.from('posts').select('*,tasks(state,type)').eq('status','open');for(const p of posts||[]){const done=(t:string)=>p.tasks.filter((x:any)=>x.type===t&&x.state==='done').length;if(done('repost')>=p.repost_quota&&done('comment')>=p.comment_quota)await supabase.from('posts').update({status:'closed',closed_at:new Date().toISOString()}).eq('id',p.id)}},{timezone:'Asia/Kolkata'});
cron.schedule('0 10 * * *',async()=>{if(new Date().toLocaleString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric'}).length&&Number(new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',day:'numeric'}).format(new Date()))>=10){const {count}=await supabase.from('invoices').select('*',{count:'exact',head:true}).eq('approval_state','approved').eq('paid',false);if(count)console.info(`TODO: notify finance of ${count} unpaid invoices via email and Slack`)}},{timezone:'Asia/Kolkata'});
app.use((err:any,_req:Request,res:Response,_next:NextFunction)=>{console.error(err);res.status(err?.name==='ZodError'?400:500).json({error:err?.message||'Unexpected server error'});});
app.listen(Number(process.env.PORT)||4000,'0.0.0.0',()=>console.log('YOSO API listening'));
