-- YOSO Creator Operations & Payments Platform · Supabase / Postgres
-- Paste this whole file into Supabase SQL Editor and run once.
create type user_role as enum ('founder_finance','cofounder','account_manager','creator');
create type creator_status as enum ('active','inactive'); create type rate_status as enum ('set','pending');
create type task_type as enum ('repost','comment'); create type task_state as enum ('sent','done','rejected','timeout','reassigned');
create type targeting_mode as enum ('specific','industry','random'); create type post_status as enum ('open','closed');
create type approval_state as enum ('pending','approved','rejected'); create type bank_match as enum ('match','mismatch','unchecked');
create table users (id uuid primary key default gen_random_uuid(),email text unique not null,name text,role user_role not null default 'creator',status creator_status not null default 'active',created_at timestamptz not null default now());
insert into users(email,name,role) values ('raghvendra@yosomedia.in','Raghvendra','founder_finance'),('finance@yosomedia.in','Finance','founder_finance'),('ashish@yosomedia.in','Ashish Sangle','cofounder'),('dd@yosomedia.in','Diksha Dwivedi','cofounder'),('anshika@yosomedia.in','Anshika Gandhi','account_manager') on conflict(email) do nothing;
create table creators (id uuid primary key default gen_random_uuid(),user_id uuid references users(id) on delete set null,name text not null,email text unique not null,industry text,region text,followers integer,linkedin_url text,bank_account text,ifsc text,rate_repost numeric(10,2),rate_comment numeric(10,2),rate_campaign numeric(10,2),rate_status rate_status not null default 'pending',status creator_status not null default 'active',onboarded_at timestamptz,created_at timestamptz not null default now());
create table push_subscriptions (id uuid primary key default gen_random_uuid(),user_id uuid references users(id) on delete cascade,creator_id uuid references creators(id) on delete cascade,endpoint text unique not null,p256dh text not null,auth text not null,user_agent text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table posts (id uuid primary key default gen_random_uuid(),client text not null,link text not null,repost_quota integer not null default 0,comment_quota integer not null default 0,targeting_mode targeting_mode not null default 'random',target_industry text,created_by uuid references users(id),status post_status not null default 'open',created_at timestamptz not null default now(),closed_at timestamptz);
create table tasks (id uuid primary key default gen_random_uuid(),post_id uuid references posts(id) on delete cascade,creator_id uuid references creators(id) on delete cascade,type task_type not null,state task_state not null default 'sent',assigned_at timestamptz not null default now(),expires_at timestamptz not null default (now()+interval '2 hours'),responded_at timestamptz,screenshot_url text,reject_reason text);
create table invoices (id uuid primary key default gen_random_uuid(),creator_id uuid references creators(id) on delete cascade,month_label text not null,month_key date not null,reposts integer not null default 0,comments integer not null default 0,amount numeric(12,2),invoice_url text,invoice_name text,invoice_bank text,invoice_ifsc text,bank_match bank_match not null default 'unchecked',uploaded_at timestamptz,approval_state approval_state not null default 'pending',reject_reason text,paid boolean not null default false,paid_on date,created_at timestamptz not null default now(),unique(creator_id,month_label));
create table payments_log(id uuid primary key default gen_random_uuid(),invoice_id uuid references invoices(id) on delete cascade,amount numeric(12,2),paid_on date not null default current_date,paid_by uuid references users(id),created_at timestamptz not null default now());
create index idx_creators_industry on creators(industry); create index idx_creators_status on creators(status); create index idx_push_subscriptions_creator on push_subscriptions(creator_id); create index idx_push_subscriptions_user on push_subscriptions(user_id); create index idx_posts_status on posts(status); create index idx_tasks_state on tasks(state); create index idx_tasks_expires on tasks(expires_at); create index idx_tasks_creator on tasks(creator_id); create index idx_tasks_post on tasks(post_id); create index idx_invoices_month on invoices(month_key); create index idx_invoices_paid on invoices(paid); create index idx_invoices_approval on invoices(approval_state);
create or replace function set_rate_status() returns trigger as $$ begin new.rate_status:=case when new.rate_repost is not null and new.rate_comment is not null and new.rate_campaign is not null then 'set'::rate_status else 'pending'::rate_status end; return new; end; $$ language plpgsql;
create trigger trg_rate_status before insert or update of rate_repost,rate_comment,rate_campaign on creators for each row execute function set_rate_status();
create or replace function current_role_of() returns user_role as $$ select role from users where email=(auth.jwt()->>'email') limit 1; $$ language sql stable;
create or replace function is_admin() returns boolean as $$ select current_role_of() in ('founder_finance','cofounder'); $$ language sql stable;
create or replace function is_staff() returns boolean as $$ select current_role_of() in ('founder_finance','cofounder','account_manager'); $$ language sql stable;
create or replace function my_creator_id() returns uuid as $$ select id from creators where email=(auth.jwt()->>'email') limit 1; $$ language sql stable;
alter table users enable row level security; alter table creators enable row level security; alter table push_subscriptions enable row level security; alter table posts enable row level security; alter table tasks enable row level security; alter table invoices enable row level security; alter table payments_log enable row level security;
create policy users_read_staff on users for select using(is_staff()); create policy users_read_self on users for select using(email=(auth.jwt()->>'email')); create policy users_write_admin on users for all using(is_admin()) with check(is_admin());
create policy creators_read_staff on creators for select using(is_staff()); create policy creators_read_self on creators for select using(email=(auth.jwt()->>'email')); create policy creators_update_self on creators for update using(email=(auth.jwt()->>'email')); create policy creators_admin_all on creators for all using(is_admin()) with check(is_admin());
create policy push_subscriptions_self on push_subscriptions for all using(user_id=(select id from users where email=(auth.jwt()->>'email') limit 1)) with check(user_id=(select id from users where email=(auth.jwt()->>'email') limit 1));
create policy push_subscriptions_admin on push_subscriptions for all using(is_admin()) with check(is_admin());
create policy posts_read_staff on posts for select using(is_staff()); create policy posts_insert_staff on posts for insert with check(is_staff()); create policy posts_admin_all on posts for all using(is_admin()) with check(is_admin());
create policy tasks_read_staff on tasks for select using(is_staff()); create policy tasks_read_self on tasks for select using(creator_id=my_creator_id()); create policy tasks_update_self on tasks for update using(creator_id=my_creator_id()); create policy tasks_staff_write on tasks for all using(is_staff()) with check(is_staff());
create policy invoices_read_admin on invoices for select using(is_admin()); create policy invoices_read_self on invoices for select using(creator_id=my_creator_id()); create policy invoices_insert_self on invoices for insert with check(creator_id=my_creator_id() or is_admin()); create policy invoices_admin_all on invoices for all using(is_admin()) with check(is_admin());
create policy payments_admin on payments_log for all using(is_admin()) with check(is_admin());
-- API additionally strips all rate fields from creator self-updates. Service-role scheduler bypasses RLS.
